#!/bin/zsh

# Script Name: clone
# Description: This script clones a GitHub repository and opens it in VS Code.
# Usage: clone <github_repo_url> [folder_name]
# Author: Your Name


# Check for correct number of arguments
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: clone <github_repo_url> [folder_name]"
    exit 1
fi

# GitHub URL
GITHUB_URL=$1

# Extract repository name from URL
REPO_NAME=$(basename -s .git $GITHUB_URL)

# Base directory where you want to clone the repo
BASE_DIR="/Users/braden/Projects/"

# Additional folder name if specified
if [ "$#" -eq 2 ]; then
    ADDITIONAL_FOLDER=$2
    CLONE_DIR="$BASE_DIR/$ADDITIONAL_FOLDER"

    if [ ! -d "$CLONE_DIR" ]; then
        read -q "REPLY?The folder $ADDITIONAL_FOLDER does not exist. Would you like to create it? (y/n)"
        echo ""
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            mkdir -p "$CLONE_DIR" || { echo "Failed to create directory"; exit 1; }
        else
            echo "Exiting..."
            exit 1
        fi
    fi
else
    CLONE_DIR=$BASE_DIR
fi

# Change to the specified directory
cd "$CLONE_DIR" || { echo "Directory $CLONE_DIR does not exist"; exit 1; }

# Clone the repository
git clone $GITHUB_URL || { echo "Failed to clone repository"; exit 1; }

# Change to the repository directory
cd "$REPO_NAME" || { echo "Failed to navigate to repository directory"; exit 1; }

# Open in a new VS Code window
code . || { echo "Failed to open VS Code"; exit 1; }